### ISSUE TITLE
Person segment quality need improvement

### ISSUE THREAD

**Issue by jiangjianping** [floe/deepbacksub#21]
Encounter the issues with both two models:
1. one of person part missing sometimes
2. person is twinkling

**Comment by floe** [comment]
1. I _think_ this is because both body-pix and deeplabv3 have mostly been trained with full-body images of persons. Fixing this would probably involve retraining the networks with pictures containing upper-body images (like in a typical webcam view).
2. This could perhaps be fixed by using an average mask like https://github.com/allo-/virtual_webcam_background does.

**Comment by jiangjianping** [comment]
I think so. the second can be improved firstly as allo's solution.

**Comment by jiangjianping** [comment]
@floe ,

Could you modify to  average masks to decrease the flickering?

**Comment by jiangjianping** [comment]
@floe ,

do you have this plan (to enhance with average masks)?

**Comment by floe** [comment]
Yes, but I'm currently moving house, so this might take until end of August.

**Comment by jiangjianping** [comment]
If the cpp version needs numpy, this may have help: https://github.com/dpilger26/NumCpp
